print( 'hello word' )
print(type ('helo print'))
print (type(1))
print (type(2.0))
print('1'+'1')
print(True , False)
print(type(True)  ,type (False))
print((5==5 and 10<5))
print((5>3 or 7==10))
print((int('5')))
print((type(int('5'))))
print((type('hello')))